name: Build Busuanzi-Serv00

on:
  schedule:
    - cron: '0 16 */1 * *'
  workflow_dispatch:

env:
  GITHUB_NAME: ${{ secrets.GH_NAME }} # 你的github昵称
  GITHUB_EMAIL: ${{ secrets.GH_EMAIL }} # 你的github邮箱
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # github token

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Busuanzi-Serv00
    steps:
    - uses: actions/checkout@v4
    - name: Build Busuanzi-Serv00
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y node wget curl git go121 gcc bash gawk gsed
          ln -s /usr/local/bin/go121 /usr/local/bin/go
        run: |
          export LATEST_APP=$(wget -qO- https://api.github.com/repos/soxft/busuanzi/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
          git clone -b $LATEST_APP https://github.com/soxft/busuanzi.git && cd busuanzi
          go build -o busuanzi main.go
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: Busuanzi-Serv00
        path: |
            busuanzi

    - name: Generate release tag
      id: tag
      run: echo "release_tag=$(wget -qO- https://api.github.com/repos/soxft/busuanzi/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              busuanzi
              
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'SinzMise/busuanzi'
        retain_days: 1
        keep_minimum_runs: 8
